name: iotdevice-node-red-demo
adopt-info: node-red
summary: Low-code programming for event-driven applications
description: Node-RED is a flow based programming application for wiring together hardware devices, APIs and online services in new and interesting ways. For more information see http://nodered.org
confinement: strict
grade: stable
base: core22

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: [amd64, arm64]
    build-for: arm64
  - build-on: [amd64, armhf]
    build-for: armhf

apps:
  node-red:
    command: bin/startNR
    daemon: simple
    restart-condition: on-failure
    plugs:
      - audio-playback
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
      - snapd-control
  npm:
    command: bin/npm
    plugs:
      - home
      - network
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop
  node:
    command: bin/node
    plugs:
      - audio-playback
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
      - snapd-control

parts:
# HOST PARTS
  cross-build-utils.host:
    source: https://github.com/dbruno74/cross-build-utils.git
    plugin: nil
    override-pull: |
        craftctl default
        . $CRAFT_PART_SRC/install/cross-install

  node.host: # We dump in a specific version of node/npm from upstream for building on host only. Note that it is not installed/staged
    after: [cross-build-utils.host]
    plugin: dump
    source:
    # native
      - on amd64 to amd64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.gz
      - on armhf to armhf: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-armv7l.tar.gz
      - on arm64 to arm64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-arm64.tar.gz
    # cross
      - on amd64 to armhf: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.gz
      - on amd64 to arm64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.gz
    override-pull: |
         craftctl default
         . $CRAFT_PROJECT_DIR/install/node.host-install
    override-build: |
         . ~/.cross-env
         prepare
         npm install --no-audit --no-fund --global @mapbox/node-pre-gyp
         echo module node-pre-gyp installed on $HOST_ARCH

# TARGET PARTS
  node: # We dump in a specific version of node/npm from upstream for staging/priming
    after: [node-red]
    plugin: dump
    source:
    # native
      - on amd64 to amd64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.gz
      - on armhf to armhf: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-armv7l.tar.gz
      - on arm64 to arm64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-arm64.tar.gz
    # cross
      - on amd64 to armhf: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-armv7l.tar.gz
      - on amd64 to arm64: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-arm64.tar.gz
    override-build: |
      . ~/.cross-env
      prepare
      craftctl default

  node-red:
    after: [node.host]
    plugin: nil
    source: .
    build-packages:
      - python3
      - sudo
      - libcap2-bin
    stage-packages:
    # native builds
      - on amd64 to amd64:
         - python3:amd64
         - libatomic1:amd64
         - bluetooth:all
         - bluez:amd64
         - libbluetooth3:amd64
         - libbluetooth-dev:amd64
         - libssl3:amd64
         - libssl-dev:amd64
         - libudev1:amd64
         - libudev-dev:amd64
         - libusb-1.0-0:amd64
         - libusb-1.0-0-dev:amd64
         - curl:amd64
      - on arm64 to arm64:
         - python3:arm64
         - libatomic1:arm64
         - bluetooth:all
         - bluez:arm64
         - libbluetooth3:arm64
         - libbluetooth-dev:arm64
         - libssl3:arm64
         - libssl-dev:arm64
         - libudev1:arm64
         - libudev-dev:arm64
         - libusb-1.0-0:arm64
         - libusb-1.0-0-dev:arm64
         - curl:arm64
      - on armhf to armhf:
         - python3:armhf
         - libatomic1:armhf
         - bluez:armhf
         - libbluetooth3:armhf
         - libbluetooth-dev:armhf
         - libssl3:armhf
         - libssl-dev:armhf
         - libudev1:armhf
         - libudev-dev:armhf
         - libusb-1.0-0:armhf
         - libusb-1.0-0-dev:armhf
         - curl:armhf
   # cross builds
      - on amd64 to arm64:
         - python3:arm64
         - libatomic1:arm64
         - bluez:arm64
         - libbluetooth3:arm64
         - libbluetooth-dev:arm64
         - libssl3:arm64
         - libssl-dev:arm64
         - libudev1:arm64
         - libudev-dev:arm64
         - libusb-1.0-0:arm64
         - libusb-1.0-0-dev:arm64
         - curl:arm64
      - on amd64 to armhf:
         - python3:armhf
         - libatomic1:armhf
         - bluez:armhf
         - libbluetooth3:armhf
         - libbluetooth-dev:armhf
         - libssl3:armhf
         - libssl-dev:armhf
         - libudev1:armhf
         - libudev-dev:armhf
         - libusb-1.0-0:armhf
         - libusb-1.0-0-dev:armhf
         - curl:armhf
    override-build: | 
      . ~/.cross-env
      prepare-gcc 

      npm config set unsafe-perm true

      # compile and install bluetooth-hci-socket module
      npm install --no-audit --no-fund --prefix $CRAFT_PART_INSTALL/lib --ignore-scripts @abandonware/bluetooth-hci-socket
      cd $CRAFT_PART_INSTALL/lib/node_modules/@abandonware/bluetooth-hci-socket && /lib/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp install --fallback-to-build --target_arch=$CRAFT_TARGET_ARCH

      # install global modules
      npm install --no-audit --no-fund --prefix $CRAFT_PART_INSTALL/lib utf8 uuid node-red node-red-node-ping node-red-node-random node-red-node-serialport node-red-node-data-generator node-red-dashboard node-red-contrib-ui-multistate-switch node-red-node-ui-table node-red-contrib-ui-media node-red-contrib-tableify node-red-contrib-ui-led node-red-contrib-controltimer @dbruno74/node-red-node-sensortag @dbruno74/node-red-node-snapd

      # some cleaning ...
      find $CRAFT_PART_INSTALL -type f -name '*.js.swp' -delete
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name test -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name doc -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name example -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name sample -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -iname benchmark* -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -iname .nyc_output -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -iname unpacked -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name man* -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -name tst -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type d -iname demo -prune -exec rm -rf {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -name bench.gnu -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -name .npmignore -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -name .travis.yml -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -name .jshintrc -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname README.md -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname HISTORY.md -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname CONTRIBUTING.md -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname CHANGE*.md -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitmodules -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitattributes -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitignore -exec rm -f {} \;
      find $CRAFT_PART_INSTALL/lib/node_modules -type f -iname "*~" -exec rm -f {} \;

      # setting snap version
      VER=$(npm show node-red version)
      echo "VERSION $(npm show node-red version)"
      craftctl set version=$VER

  settings:
    plugin: dump
    after: [node]
    source: snap/local/settings 
    organize:
      start.sh: "bin/startNR"
      desktop-launch: "bin/desktop-launch"
    override-build: |
      . ~/.cross-env
      prepare
      craftctl default

  config:
    source: config
    after: [node]
    plugin: dump
    override-build: |
      . ~/.cross-env 
      prepare
      craftctl default

plugs:
  writable:
    interface: content
    content: writable-data
    target: $SNAP_DATA/grafana



